@extends('pages.association')

@section('content')

  <h1>History</h1>

  <p>T.F.V. ‘Professor Francken’ has the honour to have two very much appreciated physicists as honorary members. Of course professor J.C. Francken, after whom we named the association, is an honorary member. And of course professor J.Th.M. De Hosson became an honorary member on basis of his special merit towards the association</p>

  <hr>

  <h2>J.C. Francken †</h2>

  <p>Professor J.C. Francken was born on 29 March 1919 in Surabaya in the former Dutch East Indies, and took his school-leaving examination in 1937 at the grammar school in Medan, where his father was principal. He then went to Delft Technical College (now Delft University of Technology) to study physics. After passing his propaedeutic (first-year) examination in 1939 he paid a visit to his parents in Semarang, planning to continue his studies in Delft in September of that year. In fact it was January 1946 before he was able to do so. For over six years he was in the former Royal Dutch East Indies Army (KNIL). From March 1942 to August 1945 he was held prisoner of war by the ‘Imperial’ Japanese army, first in Malang and from 1943 on the Burma railway in Thailand (not a period that merited the description ‘imperial’).</p>

  <p>In 1946 Francken returned to Delft, where he passed his ingenieur’s examination as a member of the Electron Optics Group under Prof. H.B. Dorgelo in 1948. The next year he moved to the Philips Physics Laboratory in Eindhoven, where he was a member of the Electron Optics Group directed by Prof. H.B. Casimir. There he worked on electron optics images in the iconoscope, the television camera tube, and gained his PhD for this work under Prof. Dorgelo in Delft on 17 June 1953. He was awarded the predicate ‘with honours’ for his thesis, entitled ‘Electron Optics of the Image Iconoscope’. After working for a while as chief engineer at the Cathode Ray Tube Development Department of Philips’ Electron Tubes Division, he was appointed Professor of Applied Physics at the University of Groningen by Royal Decree of 3 July 1962 and took up his post on 1 August 1962.</p>
  <p>During the ensuing 22 years until his retirement in 1984 he unreservedly championed the separate identity of applied physics, with the aim of having it accepted as a fully-fledged ‘ingenieur’ degree programme, by both students and their future employers and, of course, the technical colleges. After the University Education Act (WWO) of 6 May 1971 was amended by Royal Decree of 2 December that year, a clause was added to the Academic Charter permitting the University of Groningen to institute a degree programme in applied physics leading to the qualification ‘ingenieur’ (ir.). During his period at Groningen Francken’s research programme evolved into various areas: initially he studied the optical properties of magnetic electron lenses, in particular the objective lens of the electron microscope, and at the time of his retirement he was working on improving output from solar collectors.</p>
  <p>To mark his departure, the Vereniging Kandidaten Technische Natuurkunde (Association of Applied Physics Kandidaats Students) announced on 18 September 1984 that it would change its name to the Professor Francken Vereniging (Professor Francken Association). This association was founded on 12 October 1984 and registered with the Chamber of Commerce under the name T.F.V. ‘Professor Francken’.</p>
  <p>After retirement Prof. Francken continued his very active involvement in the Association. The Board of the Association used to visit him every year to introduce themselves. He also took part in symposiums and enjoyed reading our magazine, Francken Vrij. In recent years he was no longer physically able to visit us, but a good deal of correspondence continued to take place between the Association and Prof. Francken.</p>
  <p>On 15 January 2007 Prof. Jan Carel Francken died at his home in Baarn at the age of 87.</p>

  <hr>

  <h2>Professor J.Th.M. De Hosson</h2>

  <p>Professor Jeff De Hosson of the Department of Applied Physics, University of Groningen (born 27th May 1950).</p>
  <p>After his PhD in applied physics (thesis: Atomic configurations and electronic structures of dislocations, with highest distinction cum laude, thesis supervisor. Prof.dr.ir. A. Wegener Sleeswyk) of the University of Groningen and his postdoctoral years in USA, Chicago and UC-Berkeley, he was appointed professor in applied physics by the Crown, ‘Koninklijk Besluit 101’ 6th October, 1977 at the University of Groningen.</p>
  <p>His research focuses on electron microscopy, dislocation dynamics, and interface science related to surface engineering. He published more than 800 scientific publications, a/o. 32 chapters in books, edited 12 books and so far he supervised 69 PhDs and 316 master students. His scientific responsibilities include numerous editorships of international scientific journals, a/o principal editor of the J. Nanoscience and Nanotechnology, associate editor Acta Materialia/Scripta Materialia and member of the board of Governors of Acta Materialia Inc, USA, editorial boards Encyclopedia Nano Science and Nanotechnology,Current NanoScience, Surface Coating & technology; Surface Engineering, Interface Science, Computational Materials Science, Materials Science Forum, Microstructure and Materials Properties, High temperature materials and processes..</p>
  <p>In 1998 he was elected honorary member of the Applied Physics student association T.F.V. ‘Professor Francken’.</p>
  <p>He is elected member of the “The Royal Holland Society of Sciences and Humanities”, of the “Royal Netherlands Academy of Arts and Sciences” (KNAW) division physics and vice -chairman of the council Physics and Astronomy of the KNAW. In 2002 he was elected Fellow of the American Society for Metals (FASM), followed by the Acta Materialia Inc award in 2003. In 2004 he became Fellow of the Wessex Institute of Great Britain. In 2005 he received the Eminent Scientist Medal of Wessex Institute of Great Britain/University of Southampton and the European Materials Gold Medal of the Federation of European Materials Societies (FEMS). He is acting chairman of the division Applied Sciences of the Royal Netherlands Academy of Arts and Sciences (KNAW, Koninklijke Nederlandse Akademie van Wetenschappen, division physics/ afdeling natuurkunde), 2006-present. In 2008 he became elected Fellow International Society Nanoscience and Nanotechnolgy, and received the Nanostructured Materials Award, NanoSmatPrize as well as the prestigious TMS -Triple M (Materials Metals Minerals) Society USA Fellow Award in 2009. In 2010 he was the recipient of the Lee Hsun award of the Chinese Academy of Sciences (Shenyang) and the China Distinguished Materials Scientists Forum Award (Beijing). He holds Honorary Guest Professorships at Tsinghua University (Beijing-China), the Nelson Mandela Metropolitan University (South Africa) and the University of Science and Technology, Beijing-China.</p>

@endsection
